### ISSUE TITLE
컴포넌트 생성

### ISSUE THREAD

**Issue by dalcon10028** [back1ash/csv-grid#3]
아래 프로젝트 형태로 컴포넌트를 만들어주세요.
추가 요구사항은 선택입니다.

```javascript
.
├── App.js
├── components
│   ├── FileLoad.js
│   └── Grid.js
└── main.js
```
## 요구사항
- [x] csv 파일을 읽을 수 있는 input이 존재해야 합니다.
- [x] SlickGrid를 렌더링 할 수 있는 영역이 존재해야 합니다.

## 추가 요구사항
- [x] 디자인 라이브러리(BootStrap Buefy...)를 사용하여 보기 좋게 퍼블리싱 합니다.
- [x] `Component.js` 를 작성하여 추상화 된 컴포넌트를 작성합니다.

**Comment by back1ash** [comment]
@dalcon10028 
feature/component 브랜치를 만들어 해당 이슈를 해결했습니다.
PR을 작성하고 main에 merge하려고 했으나 충돌이 있는데, 충돌 해결 후에 PR 작성하면 될까요?
